### ISSUE TITLE
neoloop-caller IndexError

### ISSUE THREAD

**Issue by zzhoujialu** [XiaoTaoWang/NeoLoopFinder#43]
Dear author,
I conducted the same analytical strategy on a series of data from one dataset but come across the following error in one of them. I have no idea why it happens.

**IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed**

My command line: neoloop-caller -O new.neo-loops.txt --assembly new.assemblies.txt --balance-type CNV --protocol insitu --prob 0.95 --nproc 4 -H /path/to/my/mcool/file::resolutions/50000 /path/to/my/mcool/file::resolutions/10000 /path/to/my/mcool/file::resolutions/5000

And here is part of my new.assemblies.txt file.
![截屏2023-02-16 16 32 44](https://user-images.githubusercontent.com/97088260/219310678-20d341f7-3c98-42da-a9ab-2430cc5706b2.png)

I used **cooler dump** to check those cool files and found no difference in file format. Could you give me any suggestions?
Looking forward to hearing from you. Really appreciate your help!
Yours sincerely,
kalo.

**Comment by XiaoTaoWang** [comment]
Hi, thanks for the feedback. Can you provide the full error message, so that I can debug?

**Comment by zzhoujialu** [comment]
Thanks! Here is my error message: 

ARGUMENT LIST:
Output Path = new.neo-loops.txt
Cache Folder = .cache
SV assembly = new.assemblies.txt
Cooler List = ['/path/to/my/mcool/file::resolutions/50000 /path/to/my/mcool/file::resolutions/10000 /path/to/my/mcool/file::resolutions/5000']
Extended Genomic Span = 3000000bp
Balance Type = CNV
Probability threshold = 0.95
No pooling = False
Minimum marginal peaks = 2
Number of Processes = 4
Log file name = neoloop.log
![截屏2023-02-17 10 27 50](https://user-images.githubusercontent.com/97088260/219534137-d67bcb9e-9280-4068-9fab-0f533b8e7f0e.png)

**Comment by XiaoTaoWang** [comment]
Basically this error might be caused when the reconstructed matrix for an SV is either too sparse or too small in size. I just fixed this bug in the version 0.4.3-r1, can you upgrade your package by running ``pip install -U neoloop`` and try again?

**Comment by zzhoujialu** [comment]
Hi, Thank you for your prompt reply！

I successfully installed neoloop-0.4.3 but I still get the same error... 
I checked my **new.assemblies.txt** file and found 61 rows. 
And here is my cool file information (at the resolutions of 50000):

    "bin-size": 50000,
    "bin-type": "fixed",
    "creation-date": "2023-02-12T08:52:31.400557",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/4dn-dcic/hic2cool",
    "format-version": 3,
    "generated-by": "hic2cool-0.8.3",
    "genome-assembly": "/path/to/hg38.chrom.sizes",
    "hicFileScalingFactor": 1.0,
    "nbins": 62130,
    "nchroms": 195,
    "nnz": 124458497,
    "nviIndex": "0000000000000000",
    "nviLength": "0000000000000000",
    "software": "Juicer Tools Version 1.11.09",
    "storage-mode": "symmetric-upper"

Can I assume that my reconstructed matrix is not sparse or small or is there something wrong with my understanding...
Could you give me any suggestions? Thanks! :)

**Comment by XiaoTaoWang** [comment]
double check to make sure your neoloop version is 0.4.3-r1, but not 0.4.3?

**Comment by zzhoujialu** [comment]
Great! That works.
